accounts:
  - name: alice
    coins: [ "200000000uflix" ]
  - name: bob
    coins: [ "100000000uflix" ]
validator:
  name: alice
  staked: "100000000uflix"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: [ "100000uflix" ]
genesis:
  chain_id: "omniflix-devnet-3"
  app_state:
    staking:
      params:
        bond_denom: "uflix"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "uflix"
    mint:
      params:
        mint_denom: "uflix"
    crisis:
      constant_fee:
        amount: "1000"
        denom: "uflix"
