# This is a basic workflow that is manually triggered

name: omniflixhub

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
      - "v[0-9]**"
  workflow_dispatch:

env:
  GO_VERSION: "1.20.5"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    name: omniflixhub ${{ matrix.arch }} for ${{ matrix.targetos }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
        targetos: [ darwin, linux ]
        include:
          - targetos: darwin
            arch: arm64

    steps:
      - name: Setup Golang
        uses: actions/setup-go@v4
        if: env.GIT_DIFF
        with:
          go-version: ${{env.GO_VERSION}}
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile
        run: |
          go mod download
          cd cmd/omniflixhubd
          go build .

      - uses: actions/upload-artifact@v3
        with:
          name: omniflixhubd ${{ matrix.targetos }} ${{ matrix.arch }}
          path: cmd/omniflixhubd/omniflixhubd

